"""Browser controls for the local catalog job runner."""

JOB_STYLES = """
    .library-tools{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:14px}.library-tools button{min-height:36px;font-size:12px}.library-tools .add-elements{border-color:#386552;color:var(--accent2)}
    .job-status{margin:0 0 18px;padding:12px 0;border-block:1px solid var(--line)}.job-status h2{margin:0;font-size:14px}.job-status progress{width:100%;height:8px;margin:10px 0;accent-color:var(--accent)}.job-status p{margin:4px 0;color:var(--muted);font-size:12px;overflow-wrap:anywhere}.job-status pre{max-height:180px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;font:11px/1.6 ui-monospace,monospace}.job-status summary{cursor:pointer;color:var(--muted);font-size:11px}.job-head{display:flex;justify-content:space-between;align-items:center;gap:8px}.job-message.error{color:var(--red)}
    .jobs-dialog{width:min(600px,calc(100vw - 24px));max-height:calc(100dvh - 32px);overflow:auto;padding:24px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.jobs-dialog::backdrop{background:rgba(0,0,0,.65)}.jobs-dialog h2{margin:0 0 20px;font-size:20px}.jobs-dialog form{display:grid;gap:14px}.jobs-dialog label{font-size:12px;color:#c4cbd4}.jobs-dialog input:not([type=checkbox]),.jobs-dialog select{width:100%;min-width:0;padding:0 10px;margin-top:5px}.jobs-dialog input[type=checkbox]{min-height:0;width:16px;height:16px;accent-color:var(--accent);flex-shrink:0;margin:0}.jobs-dialog .check-label{display:flex;align-items:center;gap:9px}.jobs-dialog .button-row{justify-content:flex-end;margin-top:8px}.folder-entry{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end}.folder-entry button{min-height:40px}.folder-browser{padding:12px 0;border-block:1px solid var(--line)}.folder-browser[hidden]{display:none}.folder-browser header{display:flex;align-items:center;gap:10px;margin-bottom:10px}.folder-browser code{font-size:11px;overflow-wrap:anywhere;min-width:0}.folder-list{max-height:230px;overflow:auto}.folder-list button{display:block;width:100%;padding:10px 8px;border:0;border-bottom:1px solid var(--soft);background:transparent;color:var(--text);text-align:left;overflow-wrap:anywhere}.folder-list button:hover{background:var(--panel2)}.folder-browser footer{display:flex;justify-content:flex-end;margin-top:10px}.job-error,.analysis-availability{color:var(--amber);font-size:12px;margin:0;overflow-wrap:anywhere}.job-error{color:var(--red)}.force-selection{max-height:220px;overflow:auto;border-block:1px solid var(--line);padding:8px 0}.force-selection label{padding:7px 0;overflow-wrap:anywhere}.jobs-dialog button:disabled,.library-tools button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:720px){.jobs-dialog{padding:18px}.library-tools{gap:6px}.library-tools button{font-size:11px;padding:0 8px}}
"""

JOB_TOOLBAR = """
    <div class="library-tools" id="library-tools" aria-label="Library operations">
      <button type="button" class="quiet-button add-elements" id="add-elements">Add elements</button>
      <button type="button" class="quiet-button" id="process-pending">Process pending</button>
      <button type="button" class="quiet-button" id="force-reprocess">Force reprocess</button>
    </div>
    <p class="analysis-availability" id="analysis-availability" hidden></p>
    <section class="job-status" id="job-status" aria-label="Library job" hidden>
      <div class="job-head"><h2 id="job-heading"></h2><button type="button" class="quiet-button" id="cancel-job">Stop after current item</button></div>
      <progress id="job-progress" aria-label="Job progress"></progress>
      <p id="job-count"></p><p id="job-current"></p><p class="job-message" id="job-message" role="status"></p>
      <details><summary>Job log</summary><pre id="job-log"></pre><p id="job-backup"></p></details>
    </section>
"""

JOB_DIALOGS = """
  <dialog class="jobs-dialog" id="import-dialog" aria-labelledby="import-title">
    <h2 id="import-title">Add elements</h2><form id="import-form">
      <div class="folder-entry"><label for="import-folder">Local folder<input id="import-folder" placeholder="/path/to/elements" required autocomplete="off"></label><button type="button" class="quiet-button" id="browse-folders">Browse</button></div>
      <section class="folder-browser" id="folder-browser" aria-label="Local folders" hidden><header><button type="button" class="quiet-button" id="folder-up">Up</button><code id="folder-location"></code></header><div class="folder-list" id="folder-list"></div><footer><button type="button" class="quiet-button" id="use-folder">Use this folder</button></footer></section>
      <label for="import-fps">Image sequence frame rate<input id="import-fps" type="number" min="0.001" max="240" step="any" value="24" required></label>
      <label class="check-label"><input id="import-analyse" type="checkbox" checked>Analyse imported elements</label>
      <p class="analysis-availability" id="import-availability" hidden></p><p class="job-error" id="import-error" role="alert"></p>
      <div class="button-row"><button type="button" class="quiet-button" data-close-job="import-dialog">Cancel</button><button type="submit" class="quiet-button">Add elements</button></div>
    </form>
  </dialog>
  <dialog class="jobs-dialog" id="pending-dialog" aria-labelledby="pending-title"><h2 id="pending-title">Process pending</h2><form id="pending-form">
    <label for="pending-limit">Maximum elements in this batch<input id="pending-limit" type="number" min="1" max="100000" step="1" value="20" required></label>
    <p class="job-error" id="pending-error" role="alert"></p><div class="button-row"><button type="button" class="quiet-button" data-close-job="pending-dialog">Cancel</button><button type="submit" class="quiet-button">Start analysis</button></div>
  </form></dialog>
  <dialog class="jobs-dialog" id="force-dialog" aria-labelledby="force-title"><h2 id="force-title">Force reprocess</h2><form id="force-form">
    <label for="force-scope">Reprocess<select id="force-scope"><option value="selected">Selected elements</option><option value="all">Entire catalog</option></select></label>
    <div class="force-selection" id="force-selection" role="group" aria-label="Elements to reprocess"></div>
    <label class="check-label"><input id="force-confirm" type="checkbox" required>Replace model predictions; retain artist overrides</label>
    <p class="job-error" id="force-error" role="alert"></p><div class="button-row"><button type="button" class="quiet-button" data-close-job="force-dialog">Cancel</button><button type="submit" class="quiet-button">Start forced reprocess</button></div>
  </form></dialog>
"""

JOB_SCRIPT = r"""
  <script>
    let libraryJobState=null,libraryCapability={analysis_available:false},folderState=null,lastJobRefresh='';
    const jobActive=()=>!!(libraryJobState&&['queued','running','cancelling'].includes(libraryJobState.state));
    document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.querySelector('.jobs-dialog[open]'))event.stopImmediatePropagation()},{capture:true});
    function syncLibraryBusy(){const busy=jobActive();document.querySelector('#add-elements').disabled=busy;document.querySelector('#process-pending').disabled=busy||!libraryCapability.analysis_available||!allItems.length;document.querySelector('#force-reprocess').disabled=busy||!libraryCapability.analysis_available||!allItems.length;document.querySelectorAll('[data-rating],[data-change-rater],[data-rerun],[data-preview-channel="alpha"]').forEach(x=>x.disabled=busy)}
    function openJobDialog(id){if(jobActive())return;document.querySelector('#'+id).showModal()}
    document.querySelector('#add-elements').addEventListener('click',()=>{document.querySelector('#import-error').textContent='';document.querySelector('#import-folder').value=localStorage.getItem('vfxImportFolder')||'';document.querySelector('#import-analyse').disabled=!libraryCapability.analysis_available;document.querySelector('#import-analyse').checked=libraryCapability.analysis_available;const message=document.querySelector('#import-availability');message.hidden=libraryCapability.analysis_available;message.textContent=libraryCapability.analysis_error||'';openJobDialog('import-dialog')});
    document.querySelector('#process-pending').addEventListener('click',()=>{document.querySelector('#pending-error').textContent='';openJobDialog('pending-dialog')});
    document.querySelector('#force-reprocess').addEventListener('click',()=>{document.querySelector('#force-error').textContent='';document.querySelector('#force-confirm').checked=false;document.querySelector('#force-scope').value='selected';document.querySelector('#force-selection').hidden=false;document.querySelector('#force-selection').innerHTML=allItems.map(x=>`<label class="check-label"><input type="checkbox" value="${escapeHtml(x.element_id)}" ${x.element_id===current?'checked':''}>${escapeHtml(x.name)}</label>`).join('');openJobDialog('force-dialog')});
    document.querySelector('#force-scope').addEventListener('change',event=>document.querySelector('#force-selection').hidden=event.target.value==='all');
    document.querySelectorAll('[data-close-job]').forEach(x=>x.addEventListener('click',()=>document.querySelector('#'+x.dataset.closeJob).close()));
    async function browseFolder(path){const error=document.querySelector('#import-error');error.textContent='';try{const response=await fetch('/api/folders'+(path?'?'+new URLSearchParams({path}):'')),data=await response.json();if(!response.ok)throw new Error(data.error);folderState=data;document.querySelector('#folder-browser').hidden=false;document.querySelector('#folder-location').textContent=data.path;document.querySelector('#folder-up').disabled=!data.parent;document.querySelector('#folder-list').innerHTML=data.folders.map(x=>`<button type="button" data-folder="${escapeHtml(x.path)}">${escapeHtml(x.name)}</button>`).join('')||'<p>No subfolders</p>';if(data.truncated)document.querySelector('#folder-list').insertAdjacentHTML('beforeend','<p>First 1,000 folders shown</p>');document.querySelectorAll('[data-folder]').forEach(x=>x.addEventListener('click',()=>browseFolder(x.dataset.folder)))}catch(e){error.textContent=e.message}}
    document.querySelector('#browse-folders').addEventListener('click',()=>browseFolder(document.querySelector('#import-folder').value.trim()));document.querySelector('#folder-up').addEventListener('click',()=>browseFolder(folderState?.parent));document.querySelector('#use-folder').addEventListener('click',()=>{if(folderState){document.querySelector('#import-folder').value=folderState.path;document.querySelector('#folder-browser').hidden=true}});
    async function startLibraryJob(payload,dialogId,errorId){const dialog=document.querySelector('#'+dialogId),button=dialog.querySelector('[type=submit]');button.disabled=true;document.querySelector('#'+errorId).textContent='';try{const response=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not start job');if(payload.folder)localStorage.setItem('vfxImportFolder',payload.folder);dialog.close();await renderLibraryJob(data)}catch(e){document.querySelector('#'+errorId).textContent=e.message}finally{button.disabled=false}}
    document.querySelector('#import-form').addEventListener('submit',event=>{event.preventDefault();startLibraryJob({kind:'ingest',folder:document.querySelector('#import-folder').value.trim(),default_fps:Number(document.querySelector('#import-fps').value),analyse:document.querySelector('#import-analyse').checked},'import-dialog','import-error')});
    document.querySelector('#pending-form').addEventListener('submit',event=>{event.preventDefault();startLibraryJob({kind:'pending',limit:Number(document.querySelector('#pending-limit').value)},'pending-dialog','pending-error')});
    document.querySelector('#force-form').addEventListener('submit',event=>{event.preventDefault();startLibraryJob({kind:'force',scope:document.querySelector('#force-scope').value,element_ids:[...document.querySelectorAll('#force-selection input:checked')].map(x=>x.value),confirmed:document.querySelector('#force-confirm').checked},'force-dialog','force-error')});
    document.querySelector('#cancel-job').addEventListener('click',async()=>{try{const response=await fetch('/api/jobs/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:libraryJobState.id})}),data=await response.json();if(!response.ok)throw new Error(data.error);await renderLibraryJob(data)}catch(e){document.querySelector('#job-message').textContent=e.message}});
    async function renderLibraryJob(data){libraryCapability=data;libraryJobState=data.job;const job=data.job,availability=document.querySelector('#analysis-availability');availability.hidden=data.analysis_available;availability.textContent=data.analysis_error||'';syncLibraryBusy();document.querySelector('#job-status').hidden=!job;if(!job)return;document.querySelector('#job-heading').textContent=`${label(job.kind==='ingest'?'import':job.kind)} · ${label(job.state)}`;const progress=document.querySelector('#job-progress');progress.max=Math.max(1,job.total||1);if(job.total==null&&jobActive())progress.removeAttribute('value');else progress.value=job.completed||0;document.querySelector('#job-count').textContent=`${label(job.phase)}${job.total!=null?` · ${job.completed||0}/${job.total}`:''}${job.processed!=null?` · ${job.processed} imported, ${job.reused||0} reused`:''} · ${job.errors||0} errors`;document.querySelector('#job-current').textContent=job.current||'';document.querySelector('#job-message').textContent=job.message||(job.state==='failed'?'Job failed. Inspect the job log.':jobActive()?'Artist saves paused while the catalog is updating.':'');document.querySelector('#job-message').classList.toggle('error',job.state==='failed');document.querySelector('#job-log').textContent=(job.logs||[]).join('\n');document.querySelector('#job-backup').textContent=job.backup?'Backup: '+job.backup:'';document.querySelector('#cancel-job').hidden=!jobActive();document.querySelector('#cancel-job').disabled=job.state==='cancelling';const refreshKey=`${job.id}:${job.phase}:${job.completed}:${job.state}`;if(lastJobRefresh!==refreshKey&&(job.phase==='analysis'||!jobActive())){lastJobRefresh=refreshKey;const showDetail=inspector.classList.contains('open');await loadElements();await runSearch();if(!jobActive()&&current&&showDetail)await loadDetail(current);syncLibraryBusy()}}
    async function pollLibraryJobs(){try{const response=await fetch('/api/jobs');if(!response.ok)throw new Error('Job status unavailable');await renderLibraryJob(await response.json())}catch(e){document.querySelector('#analysis-availability').hidden=false;document.querySelector('#analysis-availability').textContent=e.message}finally{setTimeout(pollLibraryJobs,1500)}}pollLibraryJobs();
  </script>
"""
