from __future__ import annotations


def review_html() -> str:
    return (REVIEW_HTML.replace("fields:selections,note:", "fields:selections,review_version:x.review_version,note:")
            .replace('<div class="layout">', '<p id="review-job-notice" role="status" hidden style="margin:0;padding:10px 18px;color:var(--amber)"></p><div class="layout">')
            .replace("</body>", REVIEW_JOB_SCRIPT + "</body>"))


REVIEW_JOB_SCRIPT = """<script>
    async function pollReviewJob(){try{const response=await fetch('/api/jobs'),data=await response.json(),busy=data.job&&['queued','running','cancelling'].includes(data.job.state);const notice=document.querySelector('#review-job-notice');notice.hidden=!busy;notice.textContent=busy?'Library updating. Review saves are paused.':'';const confirm=document.querySelector('#confirm');if(confirm)confirm.disabled=!!busy}catch(error){}finally{setTimeout(pollReviewJob,1500)}}pollReviewJob();
</script>"""


REVIEW_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Review VFX Elements</title>
  <style>
    :root{color-scheme:dark;--bg:#0c0e12;--raised:#12151b;--panel:#171b22;--panel2:#1d222b;--text:#f2f4f7;--muted:#929cab;--line:#2a303a;--soft:#222730;--accent:#74d7b5;--accent2:#8ae8c8;--amber:#f3c773;--red:#ef8d85;--blue:#8fb9f6}
    *{box-sizing:border-box}html,body{min-height:100%}body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,input,textarea{font:inherit}button{cursor:pointer}a{color:inherit;text-decoration:none}
    .topbar{position:sticky;top:0;z-index:20;display:grid;grid-template-columns:300px 1fr auto;align-items:center;min-height:68px;padding:12px 18px;background:rgba(12,14,18,.94);border-bottom:1px solid var(--line);backdrop-filter:blur(16px)}
    .back{display:inline-flex;align-items:center;gap:8px;color:#aeb7c2;font-size:12px}.back:hover{color:var(--accent)}.back span{font-size:18px}.title{text-align:center}.title strong{display:block;font-size:15px;letter-spacing:.04em}.title small{color:var(--muted)}.queue-count{padding:6px 10px;border:1px solid #5f4c29;border-radius:999px;background:#272014;color:var(--amber);font-size:11px;font-weight:700}
    .layout{display:grid;grid-template-columns:310px minmax(0,1fr);min-height:calc(100vh - 68px)}
    .queue{position:sticky;top:68px;height:calc(100vh - 68px);padding:18px 12px 30px;border-right:1px solid var(--line);overflow:auto;background:#0f1116}.eyebrow{margin:0 8px 10px;color:#687384;font-size:10px;font-weight:750;letter-spacing:.14em;text-transform:uppercase}.queue-help{margin:0 8px 15px;color:var(--muted);font-size:11px;line-height:1.5}
    .queue-item{display:grid;grid-template-columns:78px 1fr;gap:10px;width:100%;margin:5px 0;padding:8px;border:1px solid transparent;border-radius:10px;background:transparent;color:var(--text);text-align:left}.queue-item:hover{background:var(--raised)}.queue-item.active{border-color:#3e6d5d;background:#17271f}.queue-thumb{width:78px;aspect-ratio:16/9;object-fit:contain;border-radius:6px;background:#050608}.queue-name{display:block;overflow:hidden;font-size:12px;font-weight:680;text-overflow:ellipsis;white-space:nowrap}.queue-type{display:block;margin-top:2px;color:var(--accent);font-size:10px}.queue-meta{display:flex;align-items:center;gap:6px;margin-top:5px;color:#788393;font-size:9px}.issue-dot{width:6px;height:6px;border-radius:50%;background:var(--amber)}
    .review-main{min-width:0}.empty{display:grid;min-height:calc(100vh - 68px);place-items:center;padding:40px;color:var(--muted);text-align:center}.empty strong{display:block;margin-bottom:6px;color:var(--text);font-size:22px}
    .hero{display:grid;grid-template-columns:minmax(360px,52%) 1fr;min-height:360px;border-bottom:1px solid var(--line);background:#101319}.preview{position:relative;display:grid;min-height:360px;place-items:center;background:#050608}.preview video,.preview img{width:100%;height:100%;max-height:520px;object-fit:contain}.channel-switch{position:absolute;left:12px;bottom:12px;z-index:3;display:flex;padding:3px;border:1px solid rgba(255,255,255,.16);border-radius:8px;background:rgba(6,8,10,.82);backdrop-filter:blur(8px)}.channel-switch button{min-width:54px;min-height:29px;padding:0 10px;border:0;border-radius:5px;background:transparent;color:#9ba5b2;font-size:10px;font-weight:720;letter-spacing:.05em;text-transform:uppercase}.channel-switch button:hover{color:var(--text)}.channel-switch button.active{background:#e8edf2;color:#11151a}.hero-copy{display:flex;flex-direction:column;justify-content:center;padding:34px}.breadcrumb{color:var(--accent);font-size:11px;font-weight:700}.hero h1{margin:6px 0 10px;font-size:28px;line-height:1.15;letter-spacing:-.035em}.summary{margin:0;color:#c2c9d2;font-size:14px;line-height:1.65}.source-location{margin-top:15px}.source-location>span{display:block;margin-bottom:5px;color:#687383;font-size:9px;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.source-copy{display:grid;width:100%;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:9px 10px;border:1px solid var(--line);border-radius:8px;background:var(--raised);color:#8994a3;text-align:left}.source-copy:hover{border-color:#4f8e79;color:var(--text)}.source-copy code{overflow:hidden;font:10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;text-overflow:ellipsis;white-space:nowrap}.source-copy strong{color:var(--accent);font-size:10px;white-space:nowrap}.copy-status{display:block;min-height:15px;margin-top:3px;color:var(--accent);font-size:9px}.technical{margin-top:13px;color:#778291;font-size:11px}.technical span{margin-right:10px}.confidence{display:inline-flex;align-items:center;gap:6px;margin-top:16px;color:var(--amber);font-size:11px}.confidence:before{width:7px;height:7px;border-radius:50%;background:var(--amber);content:""}
    .content{max-width:980px;margin:0 auto;padding:28px 30px 60px}.section-title{margin:0 0 5px;font-size:18px}.section-copy{margin:0 0 15px;color:var(--muted);font-size:12px}.reasons{display:grid;gap:8px;margin-bottom:28px}.reason{display:flex;gap:10px;padding:11px 13px;border:1px solid #493d28;border-radius:9px;background:rgba(243,199,115,.055);color:#d2c8b6;font-size:12px;line-height:1.5}.reason b{color:var(--amber)}
    .field-list{display:grid;gap:13px}.field-card{padding:16px;border:1px solid var(--line);border-radius:11px;background:var(--raised)}.field-head{display:flex;gap:20px;align-items:flex-start;justify-content:space-between;margin-bottom:11px}.field-head h3{margin:0;font-size:14px}.field-head p{max-width:580px;margin:2px 0 0;color:var(--muted);font-size:11px}.path{color:#5f6977;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:9px}
    .options{display:flex;flex-wrap:wrap;gap:8px}.option{min-width:150px;padding:9px 10px;border:1px solid var(--line);border-radius:8px;background:var(--panel2);color:#c7ced7;text-align:left}.option:hover{border-color:#507565}.option.selected{border-color:var(--accent);background:#193128;box-shadow:0 0 0 1px var(--accent)}.option strong{display:block;color:var(--text);font-size:12px}.option small{display:block;margin-top:3px;color:#75808f;font-size:9px}.option.selected small{color:#7fb8a5}.option.custom{min-width:100px;color:var(--blue)}
    .vocabulary-picker{display:grid;grid-template-columns:150px minmax(220px,1fr);gap:10px;align-items:center;margin-top:11px;padding-top:11px;border-top:1px solid var(--soft)}.vocabulary-picker label{color:#8c97a5;font-size:10px;font-weight:700;letter-spacing:.05em;text-transform:uppercase}.vocabulary-select{width:100%;min-height:40px;padding:0 34px 0 11px;border:1px solid #3b6658;border-radius:8px;background:#111a17;color:#dce8e4;outline:none}.vocabulary-select:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(105,190,159,.1)}
    .custom-wrap{display:none;margin-top:9px}.custom-wrap.open{display:block}.custom-input{width:100%;min-height:40px;padding:9px 11px;border:1px solid #4c6280;border-radius:8px;background:#10151d;color:var(--text);outline:none}.custom-input:focus{border-color:var(--blue);box-shadow:0 0 0 3px rgba(143,185,246,.1)}.custom-help{display:block;margin-top:5px;color:#687383;font-size:10px}
    .candidates{margin:22px 0;border-top:1px solid var(--soft)}.candidates summary{padding:14px 0;color:#8994a3;cursor:pointer;font-size:11px}.candidate-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:8px}.candidate{padding:10px;border:1px solid var(--soft);border-radius:8px;background:#101319}.candidate-role{color:var(--accent);font-size:9px;text-transform:uppercase}.candidate-model{margin:3px 0;color:#7d8795;font-size:9px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.candidate-value{font-size:11px}
    .note-label{display:block;margin:22px 0 6px;font-size:11px;font-weight:650}.note{width:100%;min-height:78px;padding:10px 11px;border:1px solid var(--line);border-radius:9px;background:var(--raised);color:var(--text);resize:vertical;outline:none}.note:focus{border-color:#4f8e79}.actions{position:sticky;bottom:0;z-index:8;display:flex;gap:9px;align-items:center;justify-content:flex-end;margin:24px -30px -60px;padding:13px 30px;background:rgba(12,14,18,.94);border-top:1px solid var(--line);backdrop-filter:blur(12px)}
    .button{min-height:39px;padding:0 13px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:#c8cfd8}.button:hover{border-color:#507565}.button.primary{border-color:var(--accent);background:var(--accent);color:#092018;font-weight:720}.button.primary:hover{background:var(--accent2)}.button:disabled{cursor:wait;opacity:.55}.save-status{margin-right:auto;color:var(--muted);font-size:11px}.save-status.error{color:var(--red)}.toast{position:fixed;right:18px;bottom:18px;z-index:30;padding:11px 14px;border:1px solid #3e6d5d;border-radius:9px;background:#173128;color:var(--accent2);box-shadow:0 14px 40px rgba(0,0,0,.35);font-size:12px}
    @media(max-width:900px){.layout{grid-template-columns:240px minmax(0,1fr)}.hero{grid-template-columns:1fr}.preview{min-height:260px}.hero-copy{padding:24px}.content{padding:24px 20px 55px}.actions{margin:24px -20px -55px;padding:12px 20px}}
    @media(max-width:680px){.topbar{grid-template-columns:1fr auto}.title{display:none}.layout{display:block}.queue{position:static;height:auto;padding:10px;border-right:0;border-bottom:1px solid var(--line)}.queue-help,.eyebrow{display:none}#queue-list{display:flex;gap:5px;overflow-x:auto}.queue-item{min-width:220px}.hero{min-height:0}.preview{min-height:220px}.field-head{display:block}.path{display:block;margin-top:4px}.actions{flex-wrap:wrap}.save-status{width:100%}}
    .hero-copy{min-width:0}.hero h1,.path,.option{overflow-wrap:anywhere}.option{max-width:100%}
    @media(max-width:680px){.vocabulary-picker{grid-template-columns:minmax(0,1fr)}.vocabulary-select{min-width:0}.queue-item{flex-shrink:0}.queue-item>span{min-width:0}}
</style>
</head>
<body>
  <header class="topbar"><a class="back" href="/"><span>‹</span> Element library</a><div class="title"><strong>REVIEW QUEUE</strong><small>Human confirmation for uncertain analyses</small></div><span class="queue-count" id="queue-count">Loading…</span></header>
  <div class="layout"><aside class="queue"><p class="eyebrow">Needs review</p><p class="queue-help">Confirm the useful artist-facing tags. Your choices are stored as human overrides and survive later model runs.</p><div id="queue-list"><div class="empty">Loading queue…</div></div></aside><main class="review-main" id="review-main"><div class="empty">Loading analyses…</div></main></div>
  <script>
    const queueList=document.querySelector('#queue-list'),main=document.querySelector('#review-main'),countBadge=document.querySelector('#queue-count');let items=[],currentId=null,selections={};
    async function loadQueue(){const response=await fetch('/api/review');items=await response.json();renderQueue();if(items.length)selectItem(items[0].element_id);else renderComplete()}
    function renderQueue(){countBadge.textContent=`${items.length} to review`;queueList.innerHTML=items.length?items.map(x=>`<button type="button" class="queue-item ${x.element_id===currentId?'active':''}" data-id="${escapeHtml(x.element_id)}"><span>${x.poster_url?`<img class="queue-thumb" src="${escapeHtml(x.poster_url)}" alt="">`:'<span class="queue-thumb"></span>'}</span><span><span class="queue-name">${escapeHtml(x.name)}</span><span class="queue-type">${escapeHtml(label(x.primary_family))} › ${escapeHtml(label(x.effect_type))}</span><span class="queue-meta"><i class="issue-dot"></i>${x.review_reasons.length} concern${x.review_reasons.length===1?'':'s'} · ${Math.round(Number(x.analysis_confidence||0)*100)}%</span></span></button>`).join(''):'<div class="queue-help">Queue complete.</div>';queueList.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>selectItem(button.dataset.id)))}
    function selectItem(id){currentId=id;const item=items.find(x=>x.element_id===id);if(!item)return;selections={};item.review_fields.forEach(field=>{selections[field.path]=clone(field.current??field.options[0].value)});renderQueue();renderReview(item)}
    function renderReview(x){const media=x.preview_480_url?`<video src="${escapeHtml(x.preview_480_url)}" poster="${escapeHtml(x.poster_url||'')}" data-preview-channel-current="rgb" controls loop muted playsinline autoplay></video>`:x.poster_url?`<img src="${escapeHtml(x.poster_url)}" alt="Preview of ${escapeHtml(x.name)}">`:'No preview available';main.innerHTML=`<section class="hero"><div class="preview">${media}${previewChannelControl(x)}</div><div class="hero-copy"><div class="breadcrumb">${escapeHtml(label(x.primary_family))} <span class="arrow">›</span> ${escapeHtml(label(x.effect_type))}</div><h1>${escapeHtml(x.name)}</h1><p class="summary">${escapeHtml(x.summary||'No description available.')}</p>${sourceLocation(x)}<div class="technical"><span>${x.width||'?'} × ${x.height||'?'}</span><span>${x.fps?Number(x.fps).toFixed(2)+' fps':'fps unknown'}</span><span>${formatDuration(x.duration_seconds)}</span><span>${x.has_alpha_channel?'Alpha':'No alpha'}</span>${bestRange(x)}</div><span class="confidence">Needs review · ${Math.round(Number(x.analysis_confidence||0)*100)}% model confidence</span></div></section><div class="content"><h2 class="section-title">What needs confirmation</h2><p class="section-copy">These are the remaining doubts after the primary model, denser pass, challengers and deterministic measurements.</p><div class="reasons">${x.review_reasons.map((reason,index)=>`<div class="reason"><b>${index+1}</b><span>${escapeHtml(reason)}</span></div>`).join('')}</div><h2 class="section-title">Confirm the artist-facing tags</h2><p class="section-copy">Keep a model proposal or choose from the shared library vocabulary. Custom values are available only as a last resort.</p><div class="field-list">${x.review_fields.map(renderField).join('')}</div>${renderCandidates(x)}<label class="note-label" for="review-note">Reviewer note <span class="section-copy">(optional)</span></label><textarea class="note" id="review-note" placeholder="Why you changed a value, or anything the next model run should know…"></textarea><div class="actions"><span class="save-status" id="save-status"></span><button type="button" class="button" id="reset">Keep all selected suggestions</button><button type="button" class="button" id="skip">Skip for now</button><button type="button" class="button primary" id="confirm">Confirm choices & mark reviewed</button></div></div>`;bindReview(x)}
    function renderField(field){const vocabulary=vocabularyOptions(field);return`<section class="field-card" data-field="${escapeHtml(field.path)}"><div class="field-head"><div><h3>${escapeHtml(field.label)}</h3><p>${escapeHtml(field.reason)}</p></div><code class="path">${escapeHtml(field.path)}</code></div><div class="options">${field.options.map((option,index)=>`<button type="button" class="option ${same(option.value,selections[field.path])?'selected':''}" data-option="${index}"><strong>${escapeHtml(displayValue(option.value))}</strong><small>${escapeHtml(option.sources.join(' · '))}</small></button>`).join('')}${vocabulary.length?'':customButton()}</div>${vocabulary.length?vocabularyPicker(field,vocabulary):''}<div class="custom-wrap"><input class="custom-input" aria-label="Custom ${escapeHtml(field.label)}" placeholder="${field.multiple?'Comma-separated values':'Type a custom value'}"><span class="custom-help">${field.multiple?'Separate multiple tags with commas. Use this only when the shared vocabulary genuinely has no suitable choice.':'Use this only when the shared vocabulary genuinely has no suitable choice.'}</span></div></section>`}
    function vocabularyOptions(field){if(field.path==='effect_type'){const family=String(selections.primary_family||'unknown');return(field.vocabulary_by_family||{})[family]||[]}return field.vocabulary||[]}
    function vocabularyPicker(field,values){return`<div class="vocabulary-picker"><label for="vocabulary-${escapeHtml(field.path)}">Library vocabulary</label><select class="vocabulary-select" id="vocabulary-${escapeHtml(field.path)}" data-vocabulary aria-label="Predefined ${escapeHtml(field.label)}">${vocabularySelectOptions(field,values)}</select></div>`}
    function vocabularySelectOptions(field,values){const selected=selections[field.path];return`<option value="">Choose a predefined value…</option>${values.map(value=>`<option value="${escapeHtml(value)}" ${same(field.multiple?[value]:value,selected)?'selected':''}>${escapeHtml(label(value))}</option>`).join('')}<option value="__custom__">Custom value — last resort…</option>`}
    function customButton(){return`<button type="button" class="option custom" data-custom="true"><strong>Custom value…</strong><small>No shared vocabulary exists for this field</small></button>`}
    function bindReview(x){bindPreviewChannels(main,x);bindSourceCopy(main,x);main.querySelectorAll('[data-field]').forEach(card=>{const field=x.review_fields.find(value=>value.path===card.dataset.field);card.querySelectorAll('[data-option]').forEach(button=>button.addEventListener('click',()=>{selectOption(card,button);selections[field.path]=clone(field.options[Number(button.dataset.option)].value);if(field.path==='primary_family')refreshEffectTypeVocabulary(x)}));const picker=card.querySelector('[data-vocabulary]'),customButton=card.querySelector('[data-custom]'),wrap=card.querySelector('.custom-wrap'),input=card.querySelector('.custom-input');if(picker)picker.addEventListener('change',()=>{if(picker.value==='__custom__'){selectCustom(card,field,wrap,input);return}if(!picker.value)return;selectVocabulary(card);selections[field.path]=field.multiple?[picker.value]:picker.value;if(field.path==='primary_family')refreshEffectTypeVocabulary(x)});if(customButton)customButton.addEventListener('click',()=>selectCustom(card,field,wrap,input));input.addEventListener('input',()=>{selections[field.path]=field.multiple?input.value.split(',').map(v=>v.trim()).filter(Boolean):input.value.trim()})});document.querySelector('#reset').addEventListener('click',()=>selectItem(x.element_id));document.querySelector('#skip').addEventListener('click',skipCurrent);document.querySelector('#confirm').addEventListener('click',()=>submitReview(x))}
    function selectVocabulary(card){card.querySelectorAll('.option').forEach(value=>value.classList.remove('selected'));card.querySelector('.custom-wrap').classList.remove('open')}
    function selectCustom(card,field,wrap,input){selectVocabulary(card);const picker=card.querySelector('[data-vocabulary]');if(picker)picker.value='__custom__';wrap.classList.add('open');input.focus();selections[field.path]=field.multiple?[]:''}
    function refreshEffectTypeVocabulary(x){const card=main.querySelector('[data-field="effect_type"]');if(!card)return;const field=x.review_fields.find(value=>value.path==='effect_type'),picker=card.querySelector('[data-vocabulary]');if(!field||!picker)return;picker.innerHTML=vocabularySelectOptions(field,vocabularyOptions(field))}
    function previewChannelControl(x){return x.preview_480_url&&x.alpha_preview_url?`<div class="channel-switch" role="group" aria-label="Preview channel"><button type="button" class="active" data-preview-channel="rgb" aria-pressed="true">RGB</button><button type="button" data-preview-channel="alpha" aria-pressed="false" title="Show the grayscale alpha matte">Alpha</button></div>`:''}
    function bindPreviewChannels(root,x){const video=root.querySelector('.preview video'),buttons=root.querySelectorAll('[data-preview-channel]');if(!video||!buttons.length)return;buttons.forEach(button=>button.addEventListener('click',()=>switchPreviewChannel(video,buttons,x,button.dataset.previewChannel)))}
    function switchPreviewChannel(video,buttons,x,channel){const source=channel==='alpha'?x.alpha_preview_url:x.preview_480_url;if(!source||video.dataset.previewChannelCurrent===channel)return;const time=Number.isFinite(video.currentTime)?video.currentTime:0,wasPlaying=!video.paused;video.pause();video.src=source;video.dataset.previewChannelCurrent=channel;if(channel==='alpha')video.removeAttribute('poster');else if(x.poster_url)video.poster=x.poster_url;buttons.forEach(button=>{const active=button.dataset.previewChannel===channel;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});video.addEventListener('loadedmetadata',()=>{if(Number.isFinite(video.duration)&&video.duration>0)video.currentTime=Math.min(time,Math.max(0,video.duration-.05));if(wasPlaying)video.play().catch(()=>{})},{once:true});video.load()}
    function sourceLocation(x){return x.source_path?`<div class="source-location"><span>Source on disk</span><button type="button" class="source-copy" data-copy-source aria-label="Copy source file path" title="${escapeHtml(x.source_path)}"><code>${escapeHtml(x.source_path)}</code><strong data-copy-label>Copy path</strong></button><small class="copy-status" data-copy-status aria-live="polite"></small></div>`:''}
    function bindSourceCopy(root,x){const button=root.querySelector('[data-copy-source]');if(button&&x.source_path)button.addEventListener('click',()=>copySourcePath(x.source_path,button,root.querySelector('[data-copy-status]')))}
    async function copySourcePath(path,button,status){try{if(navigator.clipboard&&navigator.clipboard.writeText)await navigator.clipboard.writeText(path);else{const input=document.createElement('textarea');input.value=path;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}const label=button.querySelector('[data-copy-label]');label.textContent='Copied';status.textContent='Path copied to clipboard';setTimeout(()=>{label.textContent='Copy path';status.textContent=''},1800)}catch(error){status.textContent='Could not copy automatically — select the path above.'}}
    function selectOption(card,button){card.querySelectorAll('.option').forEach(value=>value.classList.toggle('selected',value===button));if(!button.dataset.custom)card.querySelector('.custom-wrap').classList.remove('open')}
    function renderCandidates(x){if(!x.candidate_summary.length)return'';return`<details class="candidates"><summary>Model and challenger proposals (${x.candidate_summary.length})</summary><div class="candidate-grid">${x.candidate_summary.map(c=>`<div class="candidate"><div class="candidate-role">${escapeHtml(label(c.role))}${c.role===x.selected_role?' · selected':''}</div><div class="candidate-model">${escapeHtml(String(c.model).split('/').pop())}</div><div class="candidate-value">${escapeHtml(label(c.primary_family||'unknown'))} › ${escapeHtml(label(c.effect_type||'unclassified'))}</div></div>`).join('')}</div></details>`}
    async function submitReview(x){const status=document.querySelector('#save-status'),button=document.querySelector('#confirm');const missing=x.review_fields.filter(field=>!present(selections[field.path]));if(missing.length){status.textContent=`Enter a value for ${missing[0].label}.`;status.className='save-status error';return}button.disabled=true;status.textContent='Saving human overrides…';status.className='save-status';try{const response=await fetch('/api/review/'+encodeURIComponent(x.element_id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:selections,note:document.querySelector('#review-note').value})}),data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Review could not be saved');items=items.filter(item=>item.element_id!==x.element_id);currentId=null;showToast(`${x.name} marked reviewed`);renderQueue();if(items.length)selectItem(items[0].element_id);else renderComplete()}catch(error){status.textContent=error.message;status.className='save-status error';button.disabled=false}}
    function skipCurrent(){if(items.length<2)return;const index=items.findIndex(x=>x.element_id===currentId);selectItem(items[(index+1)%items.length].element_id)}function renderComplete(){countBadge.textContent='Queue complete';main.innerHTML='<div class="empty"><div><strong>Review queue complete</strong>There are no analysed elements waiting for human confirmation.<br><br><a class="button" href="/">Return to element library</a></div></div>'}
    function showToast(message){const toast=document.createElement('div');toast.className='toast';toast.textContent=message;document.body.appendChild(toast);setTimeout(()=>toast.remove(),2600)}function clone(value){return JSON.parse(JSON.stringify(value))}function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}function present(value){return Array.isArray(value)?value.length>0:value!==null&&value!==undefined&&String(value).trim()!==''}function displayValue(value){return Array.isArray(value)?value.map(label).join(', '):label(value)}function label(value){return String(value||'unknown').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}function bestRange(x){const t=x.action_timing||{};if(!t.available)return'';const fps=Number(t.source_fps||x.fps||0),start=t.optimal_start_frame??Math.floor(Number(t.optimal_start_seconds||0)*fps),end=t.optimal_end_frame??Math.max(0,Math.ceil(Number(t.optimal_end_seconds||0)*fps)-1);return`<span>Best ${Number(t.optimal_start_seconds||0).toFixed(2)}s–${Number(t.optimal_end_seconds||0).toFixed(2)}s / frames ${start}–${end}</span>`}function formatDuration(value){return value==null?'Duration unknown':`${Number(value).toFixed(Number(value)<10?2:1)}s`}function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
    loadQueue();
  </script>
</body>
</html>
"""
