from __future__ import annotations
from .library_jobs_ui import JOB_STYLES, JOB_TOOLBAR, JOB_DIALOGS, JOB_SCRIPT


def index_html(categories: list[str]) -> str:
    """Return the preview-first artist library interface.

    The taxonomy is built from analysed catalog data in the browser. ``categories``
    remains accepted so older callers and custom taxonomy installs stay compatible.
    """

    _ = categories
    return (INDEX_HTML.replace("</style>", JOB_STYLES + "</style>")
            .replace('<main class="catalog">', '<main class="catalog">' + JOB_TOOLBAR)
            .replace('<dialog id="rater-dialog"', JOB_DIALOGS + '<dialog id="rater-dialog"')
            .replace("</body>", JOB_SCRIPT + "</body>"))


INDEX_HTML = r"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>VFX Element Library</title>
  <style>
    :root {
      color-scheme: dark;
      --bg:#0c0e12;--raised:#12151b;--panel:#171b22;--panel2:#1d222b;
      --text:#f2f4f7;--muted:#929cab;--line:#2a303a;--soft:#222730;
      --accent:#74d7b5;--accent2:#8ae8c8;--amber:#f3c773;--red:#ef8d85;--blue:#8fb9f6;
    }
    *{box-sizing:border-box} html,body{min-height:100%}
    body{margin:0;background:var(--bg);color:var(--text);font:14px/1.45 Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    button,input,select{font:inherit}button{cursor:pointer}
    .topbar{position:sticky;top:0;z-index:20;display:grid;grid-template-columns:240px minmax(280px,720px) 1fr;gap:18px;align-items:center;min-height:68px;padding:12px 18px;background:rgba(12,14,18,.92);border-bottom:1px solid var(--line);backdrop-filter:blur(16px)}
    .brand{display:flex;align-items:center;gap:10px}.brand-mark{display:grid;place-items:center;width:34px;height:34px;border:1px solid #3a6759;border-radius:9px;background:linear-gradient(145deg,#18362c,#101b18);color:var(--accent2);font-size:12px;font-weight:800}.brand-title{display:block;font-size:13px;font-weight:750;letter-spacing:.09em}.brand-sub{display:block;color:var(--muted);font-size:11px}
    .search-wrap{position:relative}.search-wrap svg{position:absolute;top:50%;left:13px;width:17px;color:var(--muted);transform:translateY(-50%);pointer-events:none}
    input,select{min-height:40px;border:1px solid var(--line);border-radius:9px;background:var(--raised);color:var(--text);outline:none}input:focus,select:focus{border-color:#4f8e79;box-shadow:0 0 0 3px rgba(116,215,181,.1)}
    #query{width:100%;padding:0 42px 0 41px}#clear-query{position:absolute;top:50%;right:7px;width:29px;height:29px;border:0;border-radius:7px;background:transparent;color:var(--muted);transform:translateY(-50%)}#clear-query:hover{background:var(--panel2);color:var(--text)}
    .top-stats{display:flex;align-items:center;gap:11px;justify-self:end;color:var(--muted);font-size:12px;white-space:nowrap}.top-stats strong{color:var(--text);font-size:14px}.review-link{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;border:1px solid #5f4c29;border-radius:999px;background:#272014;color:var(--amber);font-size:10px;font-weight:700;text-decoration:none}.review-link:hover{border-color:var(--amber)}
    .workspace{display:grid;grid-template-columns:240px minmax(0,1fr) 430px;min-height:calc(100vh - 68px)}
    .taxonomy{position:sticky;top:68px;height:calc(100vh - 68px);padding:18px 12px 30px;border-right:1px solid var(--line);overflow:auto;background:#0f1116}
    .eyebrow{margin:0 8px 9px;color:#687384;font-size:10px;font-weight:750;letter-spacing:.14em;text-transform:uppercase}
    .family-button,.subtype-button{display:flex;width:100%;align-items:center;justify-content:space-between;border:0;color:#b8c0cc;text-align:left}.family-button{min-height:38px;margin:2px 0;padding:0 9px;border-radius:8px;background:transparent;font-weight:650}.family-button:hover{background:var(--panel);color:var(--text)}.family-button.active{background:#193229;color:var(--accent2)}
    .count{color:#687384;font-size:11px;font-variant-numeric:tabular-nums}.family-button.active .count{color:#6fb69e}.subtypes{margin:3px 0 8px 14px;padding-left:9px;border-left:1px solid #2a433a}.subtype-button{min-height:31px;padding:4px 7px;border-radius:6px;background:transparent;font-size:12px}.subtype-button:hover,.subtype-button.active{background:#151e1b;color:var(--accent)}
    .catalog{min-width:0;padding:18px}.catalog-head{display:flex;gap:12px;align-items:center;justify-content:space-between;margin-bottom:15px}.catalog-head h1{margin:0;font-size:20px;letter-spacing:-.025em}.catalog-head p{margin:2px 0 0;color:var(--muted);font-size:12px}.controls{display:flex;gap:8px}.controls select{min-height:36px;padding:0 30px 0 9px;font-size:12px}
    #grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:14px;align-items:start}
    .element-card{display:block;min-width:0;padding:0;border:1px solid var(--soft);border-radius:12px;overflow:hidden;background:var(--raised);color:var(--text);text-align:left;transition:transform .16s,border-color .16s,box-shadow .16s}.element-card:hover,.element-card:focus-visible{border-color:#456c5f;outline:none;transform:translateY(-2px);box-shadow:0 12px 28px rgba(0,0,0,.24)}.element-card.active{border-color:var(--accent);box-shadow:0 0 0 1px var(--accent)}
    .card-media{position:relative;display:block;aspect-ratio:16/9;background:#050608;overflow:hidden}.card-media img,.card-media video{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#050608}.card-media video{opacity:0;transition:opacity .12s}.element-card.previewing video{opacity:1}.media-empty{display:grid;width:100%;height:100%;place-items:center;color:#4d5664}
    .family-chip{position:absolute;top:9px;left:9px;z-index:2;padding:4px 7px;border:1px solid rgba(255,255,255,.13);border-radius:6px;background:rgba(7,9,12,.78);color:#f7faf9;font-size:10px;font-weight:760;letter-spacing:.08em;text-transform:uppercase;backdrop-filter:blur(8px)}.preview-hint{position:absolute;right:9px;bottom:8px;z-index:2;padding:3px 6px;border-radius:5px;background:rgba(5,7,9,.72);color:#aeb7c3;font-size:10px;opacity:0}.element-card:hover .preview-hint{opacity:1}
    .card-body{display:block;padding:12px 13px 11px}.hierarchy{display:flex;align-items:center;gap:5px;color:var(--accent);font-size:11px;font-weight:680}.arrow{color:#55606d}.element-card h2{margin:5px 0 6px;overflow:hidden;font-size:14px;line-height:1.3;text-overflow:ellipsis;white-space:nowrap}.description{display:-webkit-box;min-height:38px;margin:0 0 9px;overflow:hidden;color:#b1bac6;font-size:12px;line-height:1.52;-webkit-box-orient:vertical;-webkit-line-clamp:2}
    .tag-strip{display:flex;min-height:21px;gap:5px;overflow:hidden}.mini-tag,.tag{display:inline-flex;align-items:center;max-width:100%;border:1px solid #303640;border-radius:999px;background:#1b2028;color:#b9c1cb;white-space:nowrap}.mini-tag{padding:2px 6px;font-size:10px}.tag{margin:2px 4px 2px 0;padding:4px 8px;font-size:11px}.tag.primary{border-color:#386552;background:#183127;color:var(--accent2)}.tag.secondary{color:var(--blue)}
    .rating-compact{display:flex;align-items:center;gap:5px;margin:1px 0 7px;color:var(--amber);font-size:11px}.rating-compact .rating-count{color:#687383;font-size:10px}.rating-panel{padding:12px;border:1px solid #4d4025;border-radius:9px;background:#1b1811}.rating-total{display:flex;align-items:baseline;gap:7px}.rating-total strong{color:var(--amber);font-size:20px}.rating-total span,.rating-help{color:#8d8679;font-size:10px}.rating-stars{display:flex;gap:3px;margin:9px 0 7px}.star-button{display:grid;width:35px;height:33px;padding:0;place-items:center;border:1px solid #47402f;border-radius:7px;background:#181713;color:#71684f;font-size:20px;line-height:1}.star-button:hover,.star-button.active{border-color:#9b803e;background:#292316;color:var(--amber)}.rating-person{display:flex;align-items:center;justify-content:space-between;gap:8px;color:#9a9285;font-size:10px}.rating-person button{padding:0;border:0;background:transparent;color:var(--accent);font-size:10px}
    .tech-line{display:flex;justify-content:space-between;gap:8px;margin-top:10px;color:#6f7a89;font-size:10px}.status{display:inline-flex;align-items:center;gap:5px;white-space:nowrap}.status:before{width:6px;height:6px;border-radius:50%;background:#667080;content:""}.status-accepted:before{background:var(--accent)}.status-escalated:before{background:var(--amber)}.status-needs_review:before{background:var(--red)}
    .action-track{position:relative;display:block;height:3px;margin:10px -13px -11px;background:#20252d}.action-range{position:absolute;top:0;height:100%;min-width:2px;background:var(--accent)}.action-peak{position:absolute;top:-2px;width:1px;height:7px;background:#fff}
    .inspector{position:sticky;top:68px;height:calc(100vh - 68px);border-left:1px solid var(--line);overflow:auto;background:#101319}.inspector-empty{display:grid;height:100%;padding:32px;place-items:center;color:#687383;text-align:center}.inspector-empty svg{width:45px;margin-bottom:12px;opacity:.4}
    .detail-media{position:relative;aspect-ratio:16/9;background:#050608}.detail-media video,.detail-media img{width:100%;height:100%;object-fit:contain}.close-detail{position:absolute;top:10px;right:10px;z-index:3;width:31px;height:31px;border:1px solid rgba(255,255,255,.15);border-radius:8px;background:rgba(6,8,10,.74);color:#d3d8df}.channel-switch{position:absolute;left:10px;bottom:10px;z-index:3;display:flex;padding:3px;border:1px solid rgba(255,255,255,.16);border-radius:8px;background:rgba(6,8,10,.82);backdrop-filter:blur(8px)}.channel-switch button{min-width:50px;min-height:27px;padding:0 9px;border:0;border-radius:5px;background:transparent;color:#9ba5b2;font-size:10px;font-weight:720;letter-spacing:.05em;text-transform:uppercase}.channel-switch button:hover{color:var(--text)}.channel-switch button.active{background:#e8edf2;color:#11151a}.detail-content{padding:17px 18px 32px}.detail-path{color:var(--accent);font-size:11px;font-weight:700}.detail-title{margin:5px 0 8px;font-size:20px;line-height:1.2;letter-spacing:-.025em}.detail-summary{margin:0;color:#c4cbd4;line-height:1.6}.source-location{margin-top:13px}.source-location>span{display:block;margin-bottom:5px;color:#687383;font-size:9px;font-weight:700;letter-spacing:.09em;text-transform:uppercase}.source-copy{display:grid;width:100%;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center;padding:8px 9px;border:1px solid var(--line);border-radius:8px;background:var(--raised);color:#8994a3;text-align:left}.source-copy:hover{border-color:#4f8e79;color:var(--text)}.source-copy code{overflow:hidden;font:10px/1.35 ui-monospace,SFMono-Regular,Menlo,monospace;text-overflow:ellipsis;white-space:nowrap}.source-copy strong{color:var(--accent);font-size:10px;white-space:nowrap}.copy-status{display:block;min-height:15px;margin-top:3px;color:var(--accent);font-size:9px}
    .section{margin-top:18px;padding-top:15px;border-top:1px solid var(--soft)}.section h3{margin:0 0 9px;color:#8994a3;font-size:10px;letter-spacing:.12em;text-transform:uppercase}.tag-row{display:grid;grid-template-columns:104px 1fr;gap:9px;padding:5px 0}.tag-label{padding-top:5px;color:#687383;font-size:11px}.tag-values{min-width:0}
    .timeline-card{padding:11px;border:1px solid var(--line);border-radius:9px;background:var(--raised)}.timeline-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:10px}.timeline-bar{position:relative;height:8px;margin:9px 0 7px;border-radius:999px;background:#29303a}.timeline-visible,.timeline-optimal{position:absolute;height:100%;border-radius:inherit}.timeline-visible{background:#566170}.timeline-optimal{background:var(--accent)}.timeline-peak{position:absolute;top:-3px;width:2px;height:14px;background:#fff}.timeline-copy{color:#aeb7c2;font-size:11px}
    .technical-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.technical-cell{padding:8px 9px;border:1px solid var(--soft);border-radius:7px;background:var(--raised)}.technical-cell span{display:block;color:#687383;font-size:9px;letter-spacing:.08em;text-transform:uppercase}.technical-cell strong{display:block;margin-top:2px;color:#d7dce2;font-size:12px;font-weight:600}.review-callout{padding:10px;border-left:2px solid var(--amber);background:rgba(243,199,115,.06);color:#c8c0af;font-size:11px}
    .pipeline-details{margin-top:18px;border-top:1px solid var(--soft)}.pipeline-details summary{padding:14px 0;color:#8994a3;cursor:pointer;font-size:11px;font-weight:650}.button-row{display:flex;flex-wrap:wrap;gap:6px}.quiet-button{min-height:31px;padding:0 9px;border:1px solid var(--line);border-radius:7px;background:var(--panel);color:#c2c9d2;font-size:11px}.quiet-button:hover{border-color:#4f8e79;color:var(--accent)}.source-path{margin:9px 0;color:#748091;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;overflow-wrap:anywhere}
    .empty-results{grid-column:1/-1;padding:70px 20px;color:var(--muted);text-align:center}.loading{padding:50px 10px;color:var(--muted);text-align:center}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
    .load-more{grid-column:1/-1;min-height:42px;border:1px solid var(--line);border-radius:9px;background:var(--raised);color:var(--accent);font-weight:650}.load-more:hover{border-color:#4f8e79;background:var(--panel)}
    @media(max-width:1180px){.workspace{grid-template-columns:220px minmax(0,1fr)}.inspector{position:fixed;top:68px;right:0;z-index:15;width:min(430px,92vw);box-shadow:0 18px 55px rgba(0,0,0,.35);transform:translateX(102%);transition:transform .2s}.inspector.open{transform:translateX(0)}}
    @media(max-width:720px){.topbar{grid-template-columns:1fr;gap:9px;padding:10px 12px}.brand,.top-stats{display:none}.workspace{display:block}.taxonomy{position:static;height:auto;padding:10px 12px;border-right:0;border-bottom:1px solid var(--line)}.eyebrow{display:none}#family-list{display:flex;gap:5px;overflow-x:auto}.family-button{width:auto;min-width:max-content;padding:0 10px}.family-button .count{margin-left:6px}.subtypes{display:none}.catalog{padding:13px 12px}.catalog-head{align-items:flex-start}.catalog-head h1{font-size:17px}.controls{flex-direction:column}#grid{grid-template-columns:repeat(auto-fill,minmax(220px,1fr))}.inspector{top:0;width:100vw;height:100vh}}
    .rater-dialog{width:min(400px,calc(100vw - 32px));padding:24px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:var(--text)}.rater-dialog::backdrop{background:rgba(0,0,0,.65)}.rater-dialog h2{margin:0 0 18px;font-size:18px}.rater-dialog label{display:block;margin-bottom:6px;color:var(--muted);font-size:12px}.rater-dialog input{width:100%;padding:0 10px}.rater-dialog .button-row{justify-content:flex-end;margin-top:18px}
    .detail-title{overflow-wrap:anywhere}.tag-values .tag{white-space:normal;overflow-wrap:anywhere}
    @media(max-width:720px){.topbar{grid-template-columns:minmax(0,1fr)}.top-stats{display:flex;justify-self:stretch;justify-content:space-between}.inspector{z-index:25}}
    @media(prefers-reduced-motion:reduce){*{transition-duration:.01ms!important}}
  </style>
</head>
<body>
  <header class="topbar">
    <div class="brand"><span class="brand-mark">VFX</span><span><span class="brand-title">ELEMENT LIBRARY</span><span class="brand-sub">Semantic catalog</span></span></div>
    <form id="search-form" class="search-wrap" role="search"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="m20 20-3.2-3.2"></path></svg><label class="sr-only" for="query">Search library</label><input id="query" autocomplete="off" placeholder="Search descriptions, tags or filenames…"><button id="clear-query" type="button" aria-label="Clear search">×</button></form>
    <div class="top-stats"><a class="review-link" href="/review">Review <span id="review-count">—</span></a><span><strong id="analysed-count">—</strong> analysed · <span id="total-count">—</span> total</span></div>
  </header>
  <div class="workspace">
    <nav class="taxonomy" aria-label="Element families"><p class="eyebrow">Organise by effect</p><div id="family-list"><div class="loading">Loading…</div></div></nav>
    <main class="catalog">
      <div class="catalog-head"><div><h1 id="view-title">All elements</h1><p id="result-copy">Loading catalog…</p></div><div class="controls">
        <label class="sr-only" for="status-filter">Analysis status</label><select id="status-filter"><option value="">Any review status</option><option value="accepted">Accepted</option><option value="escalated">Challenger checked</option><option value="needs_review">Needs review</option><option value="unanalysed">Not analysed</option></select>
        <label class="sr-only" for="technical-filter">Technical type</label><select id="technical-filter"><option value="">Any technical type</option><option value="alpha">Has alpha</option><option value="sequence">Image sequence</option><option value="missing">Missing frames</option></select>
        <label class="sr-only" for="sort-filter">Sort elements</label><select id="sort-filter"><option value="library">Library order</option><option value="rating">Highest rated</option><option value="rated_count">Most rated</option></select>
      </div></div>
      <section id="grid" aria-live="polite"><div class="loading">Building previews…</div></section>
    </main>
    <aside id="inspector" class="inspector" aria-label="Element details"><div class="inspector-empty"><div><svg viewBox="0 0 48 48" fill="none" stroke="currentColor"><rect x="5" y="8" width="38" height="29" rx="3"></rect><path d="m18 18 13 7-13 7z"></path></svg><br>Select an element to preview its action,<br>description, tags and technical metadata.</div></div></aside>
  </div>
  <dialog id="rater-dialog" class="rater-dialog" aria-labelledby="rater-title"><form method="dialog" id="rater-form"><h2 id="rater-title">Artist name</h2><label for="rater-name">Name shown with your ratings</label><input id="rater-name" maxlength="100" autocomplete="nickname" required><div class="button-row"><button type="button" class="quiet-button" id="rater-cancel">Cancel</button><button type="submit" class="quiet-button">Save name</button></div></form></dialog>
  <script>
    const grid=document.querySelector('#grid'),inspector=document.querySelector('#inspector'),query=document.querySelector('#query'),familyList=document.querySelector('#family-list'),statusFilter=document.querySelector('#status-filter'),technicalFilter=document.querySelector('#technical-filter'),sortFilter=document.querySelector('#sort-filter');
    let allItems=[],searchItems=null,current=null,selectedFamily='',selectedSubtype='',searchTimer=null,visibleLimit=120;
    function raterIdentity(){let id=localStorage.getItem('vfxRaterId');if(!id){id=(crypto.randomUUID?crypto.randomUUID():'browser-'+Date.now()+'-'+Math.random().toString(16).slice(2));localStorage.setItem('vfxRaterId',id)}return{id,name:localStorage.getItem('vfxRaterName')||''}}
    function requestRaterName(currentName=''){const dialog=document.querySelector('#rater-dialog'),input=document.querySelector('#rater-name');if(dialog.open)return Promise.resolve(null);input.value=currentName;dialog.returnValue='';return new Promise(resolve=>{dialog.addEventListener('close',()=>resolve(dialog.returnValue==='save'?input.value.trim().slice(0,100):null),{once:true});dialog.showModal();input.focus()})}
    async function ensureRater(){const identity=raterIdentity();if(identity.name)return identity;const name=await requestRaterName();if(!name)return null;identity.name=name;localStorage.setItem('vfxRaterName',name);return identity}
    async function loadElements(){const identity=raterIdentity(),response=await fetch('/api/elements?'+new URLSearchParams({rater_id:identity.id}));allItems=await response.json();document.querySelector('#total-count').textContent=allItems.length;document.querySelector('#analysed-count').textContent=allItems.filter(x=>x.analysis_status!=='unanalysed').length;document.querySelector('#review-count').textContent=allItems.filter(x=>x.analysis_status==='needs_review').length;renderTaxonomy();applyFilters()}
    async function runSearch(){const text=query.value.trim();if(!text){searchItems=null;applyFilters();return}try{const identity=raterIdentity(),response=await fetch('/api/search?'+new URLSearchParams({q:text,count:'80',rater_id:identity.id})),ranked=await response.json(),lexical=ranked.filter(x=>(((x.explain||{}).lexical||{}).matched_terms||[]).length);searchItems=(lexical.length?lexical.sort((a,b)=>lexicalCount(b)-lexicalCount(a)||b.score-a.score):ranked.slice(0,24))}catch(error){const terms=text.toLowerCase().split(/\s+/).filter(Boolean);searchItems=allItems.filter(x=>terms.every(term=>searchableText(x).includes(term)))}applyFilters()}
    function lexicalCount(x){return((((x.explain||{}).lexical||{}).matched_terms)||[]).length}
    function searchableText(x){return[x.name,x.summary,x.search_text,x.primary_family,x.effect_type,...(x.secondary_families||[]),...flatten(x.composition),...flatten(x.appearance),...flatten(x.motion)].join(' ').replaceAll('_',' ').toLowerCase()}
    function flatten(value){if(Array.isArray(value))return value.flatMap(flatten);if(value&&typeof value==='object')return Object.values(value).flatMap(flatten);return value==null?[]:[String(value)]}
    function taxonomy(){const families=new Map();allItems.forEach(x=>{const family=x.primary_family||'unknown',subtype=x.effect_type||'unclassified';if(!families.has(family))families.set(family,new Map());families.get(family).set(subtype,(families.get(family).get(subtype)||0)+1)});return[...families.entries()].sort((a,b)=>{if(a[0]==='unknown')return 1;if(b[0]==='unknown')return-1;const ca=[...a[1].values()].reduce((s,n)=>s+n,0),cb=[...b[1].values()].reduce((s,n)=>s+n,0);return cb-ca||a[0].localeCompare(b[0])})}
    function renderTaxonomy(){familyList.innerHTML=familyButton('','All elements',allItems.length)+taxonomy().map(([family,subtypes])=>{const count=[...subtypes.values()].reduce((s,n)=>s+n,0);const children=selectedFamily===family?`<div class="subtypes">${subtypeButton('','All '+label(family),count)}${[...subtypes.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([type,n])=>subtypeButton(type,label(type),n)).join('')}</div>`:'';return familyButton(family,label(family),count)+children}).join('');familyList.querySelectorAll('[data-family]').forEach(button=>button.addEventListener('click',()=>{selectedFamily=button.dataset.family;selectedSubtype='';visibleLimit=120;renderTaxonomy();applyFilters()}));familyList.querySelectorAll('[data-subtype]').forEach(button=>button.addEventListener('click',()=>{selectedSubtype=button.dataset.subtype;visibleLimit=120;renderTaxonomy();applyFilters()}))}
    function familyButton(value,text,count){return`<button type="button" class="family-button ${selectedFamily===value?'active':''}" data-family="${escapeHtml(value)}"><span>${escapeHtml(text)}</span><span class="count">${count}</span></button>`}
    function subtypeButton(value,text,count){return`<button type="button" class="subtype-button ${selectedSubtype===value?'active':''}" data-subtype="${escapeHtml(value)}"><span>${escapeHtml(text)}</span><span class="count">${count}</span></button>`}
    function applyFilters(){let items=searchItems||allItems;if(selectedFamily)items=items.filter(x=>x.primary_family===selectedFamily);if(selectedSubtype)items=items.filter(x=>x.effect_type===selectedSubtype);if(statusFilter.value)items=items.filter(x=>x.analysis_status===statusFilter.value);if(technicalFilter.value==='alpha')items=items.filter(x=>x.has_alpha_channel);if(technicalFilter.value==='sequence')items=items.filter(x=>x.is_sequence);if(technicalFilter.value==='missing')items=items.filter(x=>x.has_missing_frames);if(sortFilter.value==='rating')items=[...items].sort((a,b)=>Number(b.rating_quality||0)-Number(a.rating_quality||0)||Number(b.rating_count||0)-Number(a.rating_count||0)||Number(b.rating_average||0)-Number(a.rating_average||0));if(sortFilter.value==='rated_count')items=[...items].sort((a,b)=>Number(b.rating_count||0)-Number(a.rating_count||0)||Number(b.rating_quality||0)-Number(a.rating_quality||0));const total=items.length,visible=items.slice(0,visibleLimit);renderGrid(visible,total);const title=selectedSubtype?`${label(selectedFamily)} › ${label(selectedSubtype)}`:selectedFamily?label(selectedFamily):query.value.trim()?'Search results':'All elements';document.querySelector('#view-title').textContent=title;document.querySelector('#result-copy').textContent=`${visible.length<total?`${visible.length} shown of `:''}${total} ${total===1?'element':'elements'}${query.value.trim()?` matching “${query.value.trim()}”`:''}`}
    function renderGrid(items,total=items.length){if(!items.length){grid.innerHTML='<div class="empty-results"><strong>No elements match these filters.</strong><br>Try a broader family or clear the search.</div>';return}grid.innerHTML=items.map(renderCard).join('')+(items.length<total?`<button type="button" class="load-more" id="load-more">Show more · ${total-items.length} remaining</button>`:'');grid.querySelectorAll('.element-card').forEach(card=>{card.addEventListener('click',()=>loadDetail(card.dataset.id));card.addEventListener('mouseenter',()=>startPreview(card));card.addEventListener('mouseleave',()=>stopPreview(card));card.addEventListener('focus',()=>startPreview(card));card.addEventListener('blur',()=>stopPreview(card))});const more=grid.querySelector('#load-more');if(more)more.addEventListener('click',()=>{visibleLimit+=120;applyFilters()})}
    function renderCard(x){const tags=cardTags(x).slice(0,5),media=x.poster_url?`<img src="${escapeHtml(x.poster_url)}" alt="" loading="lazy">`:'<span class="media-empty">No preview</span>',video=x.preview_480_url?`<video data-src="${escapeHtml(x.preview_480_url)}" muted loop playsinline preload="none"></video>`:'';return`<button type="button" class="element-card ${x.element_id===current?'active':''}" data-id="${escapeHtml(x.element_id)}" data-testid="element-card" aria-label="Open ${escapeHtml(x.name)}"><span class="card-media">${media}${video}<span class="family-chip">${escapeHtml(label(x.primary_family))}</span>${x.preview_480_url?'<span class="preview-hint">Hover preview</span>':''}</span><span class="card-body"><span class="hierarchy"><span>${escapeHtml(label(x.primary_family))}</span><span class="arrow">›</span><span>${escapeHtml(label(x.effect_type))}</span></span><h2 title="${escapeHtml(x.name)}">${escapeHtml(x.name)}</h2>${ratingCompact(x)}<span class="description">${escapeHtml(x.summary||'No description yet.')}</span><span class="tag-strip">${tags.map(v=>`<span class="mini-tag">${escapeHtml(label(v))}</span>`).join('')}</span><span class="tech-line"><span>${technicalSummary(x)}</span><span class="status status-${escapeHtml(x.analysis_status)}">${escapeHtml(statusLabel(x.analysis_status))}</span></span>${cardTimeline(x)}</span></button>`}
    function ratingCompact(x){const count=Number(x.rating_count||0);return count?`<span class="rating-compact"><span>${'★'.repeat(Math.round(Number(x.rating_average||0)))}${'☆'.repeat(5-Math.round(Number(x.rating_average||0)))}</span><strong>${Number(x.rating_average||0).toFixed(1)}</strong><span class="rating-count">${count} rating${count===1?'':'s'}</span></span>`:'<span class="rating-compact"><span>☆☆☆☆☆</span><span class="rating-count">Not rated</span></span>'}
    function cardTags(x){const c=x.composition||{},m=x.motion||{};return[c.viewpoint,c.shot_scale,c.frame_coverage,m.speed,...(m.character||[]),...(c.edge_contact||[])].filter(v=>v&&v!=='unknown'&&v!=='none')}
    function startPreview(card){const video=card.querySelector('video');if(!video)return;if(!video.src)video.src=video.dataset.src;card.classList.add('previewing');video.play().catch(()=>{})}function stopPreview(card){const video=card.querySelector('video');if(!video)return;video.pause();card.classList.remove('previewing')}
    async function loadDetail(id){current=id;const identity=raterIdentity(),response=await fetch('/api/elements/'+encodeURIComponent(id)+'?'+new URLSearchParams({rater_id:identity.id}));renderDetail(await response.json());grid.querySelectorAll('.element-card').forEach(card=>card.classList.toggle('active',card.dataset.id===id));inspector.classList.add('open');if(typeof syncLibraryBusy==='function')syncLibraryBusy()}
    async function rerun(id,stage){const response=await fetch(`/api/rerun/${encodeURIComponent(id)}/${encodeURIComponent(stage)}`,{method:'POST'}),data=await response.json();if(!response.ok||data.error){alert(data.error||'Stage re-run failed');return}renderDetail(data);await loadElements()}
    function renderDetail(x){const s=x.semantic_analysis||{},media=x.preview_480_url?`<video src="${escapeHtml(x.preview_480_url)}" poster="${escapeHtml(x.poster_url||'')}" data-preview-channel-current="rgb" controls loop muted playsinline autoplay></video>`:x.poster_url?`<img src="${escapeHtml(x.poster_url)}" alt="Preview of ${escapeHtml(x.name)}">`:'<span class="media-empty">No preview available</span>';inspector.innerHTML=`<div><div class="detail-media">${media}${previewChannelControl(x)}<button type="button" class="close-detail" aria-label="Close details">×</button></div><div class="detail-content"><div class="detail-path">${escapeHtml(label(x.primary_family))} <span class="arrow">›</span> ${escapeHtml(label(x.effect_type))}</div><h2 class="detail-title">${escapeHtml(x.name)}</h2><p class="detail-summary">${escapeHtml(x.summary||x.caption||'No description yet.')}</p>${sourceLocation(x)}${ratingSection(x)}${timingSection(x)}<section class="section"><h3>Organisational tags</h3>${tagRow('Primary family',[x.primary_family],'primary')}${tagRow('Subtype',[x.effect_type])}${tagRow('Related families',x.secondary_families,'secondary')}</section><section class="section"><h3>Composition</h3>${groupRows(s.composition||{})}</section><section class="section"><h3>Motion & behaviour</h3>${groupRows(s.motion||{})}</section><section class="section"><h3>Appearance</h3>${groupRows(s.appearance||{})}</section><section class="section"><h3>Use in a shot</h3>${groupRows(s.usability||{})}</section><section class="section"><h3>Technical metadata</h3>${technicalGrid(x)}</section>${reviewSection(x)}<details class="pipeline-details"><summary>Pipeline & model controls</summary><div class="button-row">${['metadata','artifacts','classification','caption','motion','embedding'].map(stage=>`<button type="button" class="quiet-button" data-rerun="${stage}">Re-run ${label(stage)}</button>`).join('')}</div><div id="compare-panel"></div></details></div></div>`;inspector.querySelector('.close-detail').addEventListener('click',closeDetail);bindPreviewChannels(inspector,x);bindSourceCopy(inspector,x);inspector.querySelectorAll('[data-rerun]').forEach(button=>button.addEventListener('click',()=>rerun(x.element_id,button.dataset.rerun)));inspector.querySelectorAll('[data-rating]').forEach(button=>button.addEventListener('click',()=>rateElement(x.element_id,Number(button.dataset.rating))));const changeRater=inspector.querySelector('[data-change-rater]');if(changeRater)changeRater.addEventListener('click',changeRaterName);loadCompare(x.element_id)}
    function previewChannelControl(x){return x.preview_480_url&&x.alpha_preview_url?`<div class="channel-switch" role="group" aria-label="Preview channel"><button type="button" class="active" data-preview-channel="rgb" aria-pressed="true">RGB</button><button type="button" data-preview-channel="alpha" aria-pressed="false" title="Show the grayscale alpha matte">Alpha</button></div>`:''}
    function bindPreviewChannels(root,x){const video=root.querySelector('.detail-media video'),buttons=root.querySelectorAll('[data-preview-channel]');if(!video||!buttons.length)return;buttons.forEach(button=>button.addEventListener('click',()=>switchPreviewChannel(video,buttons,x,button.dataset.previewChannel)))}
    function switchPreviewChannel(video,buttons,x,channel){const source=channel==='alpha'?x.alpha_preview_url:x.preview_480_url;if(!source||video.dataset.previewChannelCurrent===channel)return;const time=Number.isFinite(video.currentTime)?video.currentTime:0,wasPlaying=!video.paused;video.pause();video.src=source;video.dataset.previewChannelCurrent=channel;if(channel==='alpha')video.removeAttribute('poster');else if(x.poster_url)video.poster=x.poster_url;buttons.forEach(button=>{const active=button.dataset.previewChannel===channel;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});video.addEventListener('loadedmetadata',()=>{if(Number.isFinite(video.duration)&&video.duration>0)video.currentTime=Math.min(time,Math.max(0,video.duration-.05));if(wasPlaying)video.play().catch(()=>{})},{once:true});video.load()}
    function sourceLocation(x){return x.source_path?`<div class="source-location"><span>Source on disk</span><button type="button" class="source-copy" data-copy-source aria-label="Copy source file path" title="${escapeHtml(x.source_path)}"><code>${escapeHtml(x.source_path)}</code><strong data-copy-label>Copy path</strong></button><small class="copy-status" data-copy-status aria-live="polite"></small></div>`:''}
    function bindSourceCopy(root,x){const button=root.querySelector('[data-copy-source]');if(button&&x.source_path)button.addEventListener('click',()=>copySourcePath(x.source_path,button,root.querySelector('[data-copy-status]')))}
    async function copySourcePath(path,button,status){try{if(navigator.clipboard&&navigator.clipboard.writeText)await navigator.clipboard.writeText(path);else{const input=document.createElement('textarea');input.value=path;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}const label=button.querySelector('[data-copy-label]');label.textContent='Copied';status.textContent='Path copied to clipboard';setTimeout(()=>{label.textContent='Copy path';status.textContent=''},1800)}catch(error){status.textContent='Could not copy automatically — select the path above.'}}
    function ratingSection(x){const count=Number(x.rating_count||0),average=Number(x.rating_average||0),own=Number(x.user_rating||0),identity=raterIdentity();return`<section class="section"><h3>Artist quality rating</h3><div class="rating-panel"><div class="rating-total"><strong>${count?average.toFixed(1):'—'}</strong><span>${count?`from ${count} artist${count===1?'':'s'}`:'No ratings yet'}</span></div><div class="rating-stars" role="group" aria-label="Rate this element from 1 to 5 stars">${[1,2,3,4,5].map(star=>`<button type="button" class="star-button ${star<=own?'active':''}" data-rating="${star}" aria-label="${star} star${star===1?'':'s'}">★</button>`).join('')}</div><div class="rating-person"><span>${own?`Your rating: ${own}/5`:'Choose 1–5 stars'}${identity.name?` · ${escapeHtml(identity.name)}`:''}</span><button type="button" data-change-rater>${identity.name?'Change name':'Set name'}</button></div><p class="rating-help">Ratings help quality elements surface, but never bypass semantic search relevance.</p></div></section>`}
    async function rateElement(id,rating){const identity=await ensureRater();if(!identity)return;const response=await fetch('/api/ratings/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rater_id:identity.id,rater_name:identity.name,rating})}),data=await response.json();if(!response.ok||data.error){alert(data.error||'Rating failed');return}const item=allItems.find(x=>x.element_id===id);if(item)Object.assign(item,data);if(searchItems){const searchItem=searchItems.find(x=>x.element_id===id);if(searchItem)Object.assign(searchItem,data)}await loadDetail(id);applyFilters()}
    async function changeRaterName(){const name=await requestRaterName(raterIdentity().name);if(name){localStorage.setItem('vfxRaterName',name);if(current)loadDetail(current)}}
    function closeDetail(){current=null;inspector.classList.remove('open');inspector.innerHTML='<div class="inspector-empty"><div>Select an element to preview its action,<br>description, tags and technical metadata.</div></div>';grid.querySelectorAll('.element-card').forEach(card=>card.classList.remove('active'))}
    function tagRow(name,values,className=''){const list=normalise(values);if(!list.length)return'';return`<div class="tag-row"><span class="tag-label">${escapeHtml(label(name))}</span><span class="tag-values">${list.map(value=>`<span class="tag ${className}">${escapeHtml(label(value))}</span>`).join('')}</span></div>`}
    function groupRows(group){const rows=Object.entries(group).map(([key,value])=>{const values=key==='notable_objects'?normaliseObjects(value):normalise(value);return values.length?tagRow(key,values):''}).join('');return rows||'<span class="tag-label">Not analysed yet</span>'}
    function normalise(value){if(value==null||value===''||value==='unknown')return[];return(Array.isArray(value)?value:[value]).filter(v=>typeof v!=='object'&&v!==''&&v!=='unknown').map(String)}function normaliseObjects(value){if(!Array.isArray(value))return[];return value.map(x=>x&&typeof x==='object'?[x.object,x.location].filter(Boolean).join(' · '):String(x)).filter(Boolean)}
    function timingSection(x){
      const t=(x.semantic_analysis||{}).action_timing||{},duration=Number(x.duration_seconds||0);
      if(!t.available||!duration)return'';
      const vs=percent(t.visible_start_seconds,duration),vw=percent(Number(t.visible_end_seconds||duration)-Number(t.visible_start_seconds||0),duration),os=percent(t.optimal_start_seconds,duration),ow=percent(Number(t.optimal_end_seconds||duration)-Number(t.optimal_start_seconds||0),duration),peak=percent(t.peak_seconds,duration),frames=timingFrames(t,x.fps);
      const verification=t.review_required!==false?'Timing not artist-verified':label(t.verification||'verified');
      return`<section class="section"><h3>Suggested action range</h3><div class="timeline-card"><div class="timeline-labels"><span>0:00</span><span>${formatTime(duration)}</span></div><div class="timeline-bar"><span class="timeline-visible" style="left:${vs}%;width:${vw}%"></span><span class="timeline-optimal" style="left:${os}%;width:${ow}%"></span><span class="timeline-peak" style="left:${peak}%"></span></div><div class="timeline-copy"><strong>Seconds ${formatSeconds(t.optimal_start_seconds)}–${formatSeconds(t.optimal_end_seconds)}</strong> · <strong>Frames ${frames.start}–${frames.end}</strong> <span title="Source frame numbering starts at frame 0">(0-based)</span><br>Peak ${formatSeconds(t.peak_seconds)} / frame ${frames.peak} · ${escapeHtml(label(t.pattern||'event'))}<br>${escapeHtml(verification)}</div></div></section>`
    }
    function cardTimeline(x){const t=x.action_timing||{},duration=Number(x.duration_seconds||0);if(!t.available||!duration)return'';const left=percent(t.optimal_start_seconds,duration),width=percent(Number(t.optimal_end_seconds||duration)-Number(t.optimal_start_seconds||0),duration),peak=percent(t.peak_seconds,duration),frames=timingFrames(t,x.fps);return`<span class="action-track" title="Suggested action ${formatSeconds(t.optimal_start_seconds)}–${formatSeconds(t.optimal_end_seconds)} · frames ${frames.start}–${frames.end} (0-based), not artist-verified"><span class="action-range" style="left:${left}%;width:${width}%"></span><span class="action-peak" style="left:${peak}%"></span></span>`}
    function technicalGrid(x){const cells=[['Resolution',`${x.width||'?'} × ${x.height||'?'}`],['Frame rate',x.fps?`${Number(x.fps).toFixed(2)} fps`:'Unknown'],['Duration',formatDuration(x.duration_seconds)],['Alpha',x.has_alpha_channel?(x.alpha_is_soft?'Soft alpha':'Present'):'None'],['Format',label(x.source_format||'unknown')],['Source',x.is_sequence?'Image sequence':'Movie / still'],['Bit depth',x.bit_depth?`${x.bit_depth}-bit`:'Unknown'],['Colour space',label(x.color_space||'unknown')]];return`<div class="technical-grid">${cells.map(([name,value])=>`<div class="technical-cell"><span>${escapeHtml(name)}</span><strong>${escapeHtml(value)}</strong></div>`).join('')}</div>`}
    function reviewSection(x){const uncertainty=(x.semantic_analysis||{}).uncertainty||x.uncertainty||[];return`<section class="section"><h3>Analysis review</h3>${tagRow('Status',[statusLabel(x.analysis_status)],x.analysis_status==='accepted'?'primary':'')}${tagRow('Model confidence (uncalibrated)',[`${Math.round(Number(x.analysis_confidence||0)*100)}%`])}${uncertainty.length?`<div class="review-callout">${uncertainty.map(escapeHtml).join('<br>')}</div>`:''}</section>`}
    async function loadCompare(id){const panel=document.querySelector('#compare-panel');if(!panel)return;try{const response=await fetch('/api/compare/'+encodeURIComponent(id)),data=await response.json();panel.innerHTML=data&&data.available?`<p class="source-path"><strong>${escapeHtml(data.model_a||'A')}:</strong> ${escapeHtml(data.caption_a||'')}</p><p class="source-path"><strong>${escapeHtml(data.model_b||'B')}:</strong> ${escapeHtml(data.caption_b||'')}</p><div class="button-row"><button class="quiet-button" data-vote="a">A wins</button><button class="quiet-button" data-vote="b">B wins</button><button class="quiet-button" data-vote="tie">Tie</button></div>`:'<p class="source-path">No alternate caption recorded.</p>';panel.querySelectorAll('[data-vote]').forEach(button=>button.addEventListener('click',()=>castVote(id,button.dataset.vote,panel)))}catch(error){panel.innerHTML='<p class="source-path">Caption comparison unavailable.</p>'}}
    async function castVote(id,vote,target){const response=await fetch('/api/compare/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vote})}),data=await response.json();if(data.ok)target.insertAdjacentHTML('beforeend',`<p class="source-path">Recorded: ${escapeHtml(data.vote)}</p>`)}
    function technicalSummary(x){const resolution=x.width&&x.height?`${x.width}×${x.height}`:'?×?',fps=x.fps?`${Math.round(Number(x.fps))} fps`:'? fps';return`${resolution} · ${fps} · ${formatDuration(x.duration_seconds)}${x.has_alpha_channel?' · α':''}`}
    function statusLabel(value){return({accepted:'Accepted',escalated:'Challenger checked',needs_review:'Needs review',unanalysed:'Not analysed'})[value]||label(value||'unknown')}function label(value){return String(value||'unknown').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase())}function percent(value,duration){return Math.max(0,Math.min(100,(Number(value||0)/Math.max(.001,duration))*100))}function timingFrames(t,fpsValue){const fps=Math.max(0,Number(t.source_fps||fpsValue||0)),start=t.optimal_start_frame??Math.floor(Number(t.optimal_start_seconds||0)*fps),end=t.optimal_end_frame??Math.max(0,Math.ceil(Number(t.optimal_end_seconds||0)*fps)-1),peak=t.peak_frame??Math.round(Number(t.peak_seconds||0)*fps);return{start,end,peak}}function formatSeconds(value){return`${Number(value||0).toFixed(2)}s`}function formatDuration(value){return value==null?'Unknown':`${Number(value).toFixed(Number(value)<10?2:1)}s`}function formatTime(value){const seconds=Math.max(0,Number(value||0)),minutes=Math.floor(seconds/60);return`${minutes}:${(seconds%60).toFixed(1).padStart(4,'0')}`}function escapeHtml(value){return String(value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
    document.querySelector('#rater-form').addEventListener('submit',event=>{event.preventDefault();if(document.querySelector('#rater-name').value.trim())document.querySelector('#rater-dialog').close('save')});document.querySelector('#rater-cancel').addEventListener('click',()=>document.querySelector('#rater-dialog').close('cancel'));
    document.querySelector('#search-form').addEventListener('submit',event=>{event.preventDefault();visibleLimit=120;runSearch()});document.querySelector('#clear-query').addEventListener('click',()=>{query.value='';searchItems=null;visibleLimit=120;query.focus();applyFilters()});query.addEventListener('input',()=>{clearTimeout(searchTimer);visibleLimit=120;searchTimer=setTimeout(runSearch,250)});statusFilter.addEventListener('change',()=>{visibleLimit=120;applyFilters()});technicalFilter.addEventListener('change',()=>{visibleLimit=120;applyFilters()});sortFilter.addEventListener('change',()=>{visibleLimit=120;applyFilters()});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&current&&!document.querySelector('#rater-dialog').open)closeDetail()});loadElements();
  </script>
</body>
</html>
"""
